server:
  port: 8081

spring:
  profiles:
    active: local

# Local ENV
---
spring:
  profiles: local
  datasource:
    data: classpath:data-seeder.sql
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    h2:
      console:
        enabled: true
